name: Test Secret
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print secret
        run: echo ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
